export const verbEmojiMap = {
  launched: '🚀',
  completed: '🏆',
  terminated: '❌',
  experienced: '🌐',
  viewed: '👀',
  attended: '🎓',
  interacted: '🤝',
  commented: '💬',
  answered: '📝',
  read: '📖',
  watched: '📺',
  listened: '🎧',
  created: '🎨',
  shared: '🔄',
  rated: '⭐',
  practiced: '🏋️‍♂️',
  explored: '🌍',
  evaluated: '📊',
  collaborated: '🤝',
  reviewed: '🔍',
  researched: '🕵️‍♂️',
};
