export const verbEmojiMap = {
  completed: '🎉',
  experienced: '🌐',
  passed: '✅',
  failed: '❌',
  viewed: '👀',
  attempted: '🔄',
  attended: '🎓',
  interacted: '🤝',
  commented: '💬',
  answered: '📝',
  read: '📖',
  watched: '📺',
  listened: '🎧',
  created: '🎨',
  shared: '🔄',
  rated: '⭐',
  practiced: '🏋️‍♂️',
  explored: '🌍',
  evaluated: '📊',
  collaborated: '🤝',
  reviewed: '🔍',
  researched: '🕵️‍♂️',
  launched: '🚀',
};
